services:
  - type: web
    name: seatrace-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production